#!/bin/bash

set -e

# Not really using these yet:
PROJECT=$1

sudo apt-get install -y vim curl tree unzip zip mosh aspell-en

cd $(dirname $0)

git clone https://github.com/marcusm/vimfiles.git ~/.vim

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

cp .emacs ~
cp .gemrc ~
cp .gitconfig ~
cp .profile ~
cp .tmux.conf ~

sudo cp hub /usr/local/bin

sudo wget -qO /usr/local/bin/lein https://raw.github.com/technomancy/leiningen/stable/bin/lein
